### ISSUE TITLE
Calling marching_tetrahedra outside scalarplot

### ISSUE THREAD

**Issue by panalluri** [j-fu/GridVisualize.jl#12]
Hello,

We are attempting to call `marching_tetrahedra` outside `scalarplot`. We want to manipulate the mesh outputted specifically by `marching_tetrahedra`. Upon looking into the `GridVisualize` package code, we were unable to determine exactly how to use the `marching_tetrahedra` function. Would you be able to either provide documentation or a working example of how to use the function?

**Comment by j-fu** [comment]
Hi, just added some documentation, see the development docs.  I indeed intend to keep this useful for other packages.

As for working examples:
Makie:
   https://github.com/j-fu/GridVisualize.jl/blob/fd51042692c32ab7a2149d7f798ca8d448863e19/src/makie.jl#L933
   https://github.com/j-fu/GridVisualize.jl/blob/fd51042692c32ab7a2149d7f798ca8d448863e19/src/makie.jl#L858
PyPlot:
  https://github.com/j-fu/GridVisualize.jl/blob/fd51042692c32ab7a2149d7f798ca8d448863e19/src/pyplot.jl#L513
PlutoVista:
  https://github.com/j-fu/PlutoVista.jl/blob/b6e47aa06b19bfd7e9a429054a420f8b8e4770db/src/plutovtkplot.jl#L303

Though I consider it not public, I don't plan for  major changes to this method. A couple of unit tests is still missing. Basically, it should be in another package like GridVisualizeBase (non-existing...) or Meshing.jl, still thinking about that.  Independent of any particular backend for sure.

As for further manipulation of the output: essentially what comes out is a bunch of formally unrelated triangles, I don't identify points emerging from intersection calculations on neighboring triangles, so for a smooth visual impression based on point normals this is not useful. Performance-wise I don't see this as a problem, and otherwise I see some merit in not hiding the ancestry of computed data by smoothing.

Please feel free to ask questions.

**Comment by jlchan** [comment]
Thanks for the added docs and the clarification! We can now use `marching_tetrahedra` to generate surface meshes, which is really helpful.

Does `marching_tetrahedra` also create isosurface with cuts through them? I know `scalarplot` has this functionality, but we haven't figured out what lines of code inside `scalarplot` enable this.

**Comment by j-fu** [comment]
Do you mean the planes cutting trough the viewing  domain, or do you mean the calculation of intersections of the isosurface with the planes ?

**Comment by panalluri** [comment]
I believe planes cutting through the viewing domain

**Comment by jlchan** [comment]
No, I think it should be the intersections of the isosurface with a given plane. Given an isosurface, I think `scalarplot` lets one cut through the isosurface to create something like the following picture:

![image](https://user-images.githubusercontent.com/1156048/141861907-8decc522-02e5-4b58-aa3e-dbd3bf2ba38c.png)

**Comment by j-fu** [comment]
Hi it is not completely clear from your picture what you mean (What's the program, btw ? )
Do you mean the  the sphere like isosurfaces have been cut  such that only half-spheres are visible ?

If yes, that's not possible in the moment. However a fray cut version of this should be not too hard to realize.

**Comment by jlchan** [comment]
Thanks for the clarification! I realized we can achieve a similar affect by modifying the transparency `alpha`, so @panalluri I think we can close this issue now.

**Comment by j-fu** [comment]
Yeah having transparency available makes a difference here.

**Comment by j-fu** [comment]
Hi, with v0.6 I moved marching_tetrahedra to the new package GridVisualizeTools.jl .
